interfaces = ["bonnet"]
devices = ["phone"]

[interface.bonnet]
type = "sx127x"
frequency = 910525000
sf = 7
bw = 62500
cr = 5

[device.phone]
type = "companion"
interface = "wifi"
port = 5000
name = "Green"
privatekey = "51d100a4b2deae26cb40b74f02123a3ededc23d63806be313dea4d21ff7dc2c7"
add_public_channel = true
contact_file = "contacts.mesh"
channels_file = "channels.json"
